---
- name: Demo http playbook 2
  hosts: all
  become: true
  remote_user: toweruser1
  gather_facts: no
  tasks:
  - name: login into cluster
    command: oc login -u toweruser1 -p toweruser1
  - name: create a project
    command: oc new-project towerdemo3
  - name: create a project
    command: oc new-app --docker-image=docker.io/jenkins --name=jenkindemo -n towerdemo3
  - name: set volume to app
    command: oc set volumes dc/jenkindemo --add -t pvc --name=jenkindemo-volume-1 --claim-size=2Gi --claim-name=jenkin-pvc --claim-class=storage-class-solidfire --claim-mode=RWO --overwrite  
  - name: Expose its route
    command: oc expose svc/jenkindemo -n towerdemo3    
